### ISSUE TITLE
Sejong Auth API - Request 요청 방법

### ISSUE THREAD

**Issue by ddiyoung** [iml1111/sejong-univ-auth#17]
**Is your feature request related to a problem? Please describe.**
어떤 문제로부터 해당 기능을 요청했나요?

Sejong Auth API에서 Request 방법에
POST https://auth.imsejong.com/auth HTTP/1.1
HOST : auth.imsejong.com?method=<사용하고자 하는 메소드>
로 적혀 있습니다.
실제로 Request 할 URL의 경우 auth.imsejong.com/auth?method=<사용하고자 하는 메소드> 인데
auth.imsejong.com?method=<사용하고자 하는 메소드>/auth 이런식으로 오해할 수 있을 것 같습니다.

**Describe the solution you'd like**
당신이 생각하는 해결방법을 설명해주세요.

Readme.md 부분에 해당 설명을
POST https://auth.imsejong.com/auth HTTP/1.1
HOST : auth.imsejong.com/auth?method=<사용하고자 하는 메소드>
이런식으로 변경하면 좋을 것 같습니다.

**Additional context**
추가적으로 작성하고 싶은 내용을 작성해주세요.

**Comment by iml1111** [comment]
제보 감사합니다!

**Comment by iml1111** [comment]
이게 좀 더 합리적인 설명이지 않을까 싶습니다.
```
POST https://auth.imsejong.com/auth?method=<사용하고자 하는 메소드> HTTP/1.1
Host: auth.imsejong.com
{
    "id": "<학번>",
    "pw": "<비밀번호>"
}
```
